try:
    a = 100 / 0

except Exception as erro:
    print ('Aconteceu um erro: ', erro)